# devices.yaml
# AWE Test Rig Hardware Configuration
# 
# This file contains all hardware-specific settings including:
# - NI cDAQ channel mappings and calibration
# - Serial port configurations  
# - Device communication settings
# - CALIBRATED ZERO OFFSETS for pressure/current sensors

# NI cDAQ Configuration
ni_cdaq:
  chassis: "cDAQ9187-23E902C"
  
  # NI-9253 Analog Input Module (4-20mA Current Inputs)
  analog_inputs:
    module: "cDAQ9187-23E902CMod1"
    sample_rate: 100  # Hz
    
    # 4-20mA Signal Conditioning
    current_range:
      min_ma: 4.0   # Calibrated minimum - 4mA = 0 PSI/A (updated from 3.95)
      max_ma: 20.0  # Standard maximum
      fault_threshold_low: 3.5   # Below this = DISCONNECTED
      fault_threshold_high: 20.5 # Above this = OVERRANGE
    
    # Individual Sensor Channels with Calibrated Zero Offsets
    channels:
      pressure_1:
        channel: "ai0"
        name: "PT01"
        units: "PSI"
        range: [0, 15]
        # CALIBRATED ZERO OFFSET - Corrects sensor bias at 0 PSI
        zero_offset: -0.035  # Corrects +0.035 PSI bias to achieve true 0 PSI
        description: "Hydrogen side pressure measurement"
        
      pressure_2:
        channel: "ai1" 
        name: "PT02"
        units: "PSI"
        range: [0, 15]
        # CALIBRATED ZERO OFFSET - Corrects sensor bias at 0 PSI  
        zero_offset: -0.066  # Corrects +0.066 PSI bias to achieve true 0 PSI
        description: "Oxygen side pressure measurement"
        
      current:
        channel: "ai2"
        name: "Current"
        units: "A"
        range: [0, 150]
        # CALIBRATED ZERO OFFSET - 4mA represents true 0 A
        zero_offset: 0.0  # No bias correction needed for current sensor
        description: "Electrolyzer stack current measurement"
        
      pressure_pt01:
        channel: "ai3"
        name: "PT03"
        units: "PSI"
        range: [0, 1.012]  # 0-28 inWC converted to PSI (28 * 0.036127 = 1.012)
        zero_offset: 0.0
        description: "Pressure transducer 01 (4-20mA)"
        
      pressure_pt02:
        channel: "ai4"
        name: "PT04"  
        units: "PSI"
        range: [0, 1.012]  # 0-28 inWC converted to PSI
        zero_offset: 0.0
        description: "Pressure transducer 02 (4-20mA)"
        
      pressure_pt03:
        channel: "ai5"
        name: "PT05"
        units: "PSI"
        range: [0, 1.012]  # 0-28 inWC converted to PSI
        zero_offset: 0.0
        description: "Pressure transducer 03 (4-20mA)"
        
      flowrate:
        channel: "ai6"
        name: "Flowrate"
        units: "SLM"
        range: [0, 250]  # 0-250 SLM (Standard Liters per Minute)
        zero_offset: 0.0
        description: "Gas flowrate measurement"
        
      pressure_pt05:
        channel: "ai7"
        name: "PT06"
        units: "PSI"
        range: [0, 1.012]  # 0-28 inWC converted to PSI
        zero_offset: 0.0
        description: "Pressure transducer 05 (4-20mA)"
  
  # NI-9485 Digital Output Modules (Relay Control)
  digital_outputs:
    module_2: "cDAQ9187-23E902CMod2"
    module_3: "cDAQ9187-23E902CMod3"
    
    # Valve and Pump Control Mapping
    valves:
      koh_storage:
        module: "cDAQ9187-23E902CMod2"
        line: 0
        name: "KOH Storage Valve"
        description: "Controls KOH electrolyte storage tank valve"
        
      di_storage:
        module: "cDAQ9187-23E902CMod2"
        line: 1
        name: "DI Storage Valve"
        description: "Controls deionized water storage tank valve"
        
      stack_drain:
        module: "cDAQ9187-23E902CMod2" 
        line: 2
        name: "Stack Drain Valve"
        description: "Controls electrolyzer stack drain valve"
        
      h2_purge:
        module: "cDAQ9187-23E902CMod2"
        line: 3
        name: "H2 Purge Valve"
        description: "Controls hydrogen purge valve for system cleanup"
        
      o2_purge:
        module: "cDAQ9187-23E902CMod2"
        line: 5
        name: "O2 Purge Valve"
        description: "Controls oxygen purge valve for system cleanup"
        
    pump:
      di_fill_pump:
        module: "cDAQ9187-23E902CMod2"
        line: 4
        name: "DI Fill Pump"
        description: "Controls deionized water fill pump"
        
      koh_fill_pump:
        module: "cDAQ9187-23E902CMod2"
        line: 6
        name: "KOH Fill Pump"
        description: "Controls KOH electrolyte fill pump"

# Pico TC-08 Thermocouple Logger
pico_tc08:
  device_type: "Pico TC-08"
  connection: "USB"
  
  # Temperature Channels - NO ZERO OFFSETS (raw thermocouple readings)
  channels:
    channel_0:
      name: "TC01"
      type: "K"  # Thermocouple type
      units: "°C"
      range: [0, 100]
      # NO ZERO OFFSET - Temperature sensors read direct thermocouple values
      description: "Thermocouple 1 temperature sensor"
      
    channel_1:
      name: "TC02"
      type: "K"
      units: "°C" 
      range: [0, 100]
      # NO ZERO OFFSET - Temperature sensors read direct thermocouple values
      description: "Thermocouple 2 temperature sensor"
      
    channel_2:
      name: "TC03"
      type: "K"
      units: "°C"
      range: [0, 100] 
      # NO ZERO OFFSET - Temperature sensors read direct thermocouple values
      description: "Thermocouple 3 temperature sensor"
      
    channel_3:
      name: "TC04"
      type: "K"
      units: "°C"
      range: [0, 100]
      # NO ZERO OFFSET - Temperature sensors read direct thermocouple values
      description: "Thermocouple 4 temperature sensor"
      
    channel_4:
      name: "TC05"
      type: "K"
      units: "°C"
      range: [0, 100]
      # NO ZERO OFFSET - Temperature sensors read direct thermocouple values
      description: "Thermocouple 5 temperature sensor"
      
    channel_5:
      name: "TC06"
      type: "K"
      units: "°C"
      range: [0, 100]
      # NO ZERO OFFSET - Temperature sensors read direct thermocouple values
      description: "Thermocouple 6 temperature sensor"
      
    channel_6:
      name: "TC07"
      type: "K"
      units: "°C"
      range: [0, 100]
      # NO ZERO OFFSET - Temperature sensors read direct thermocouple values
      description: "Thermocouple 7 temperature sensor"
      
    channel_7:
      name: "TC08"
      type: "K"
      units: "°C"
      range: [0, 100]
      # NO ZERO OFFSET - Temperature sensors read direct thermocouple values
      description: "Thermocouple 8 temperature sensor"

# BGA244 Gas Analyzers (3 units)
bga244:
  communication:
    protocol: "RS-422"
    interface: "USB-to-RS422"
    baud_rate: 9600
    data_bits: 8
    stop_bits: 1
    parity: "None"
    timeout: 2.0  # seconds
  
  # Three BGA244 Units (Windows COM ports)
  units:
    bga_1:
      port: "COM8"
      name: "BGA01"
      gas_types: ["H2", "O2", "N2"]
      description: "Gas analyzer on hydrogen header"
      # Gas analysis configuration for normal operation
      normal_mode:
        primary_gas: "H2"     # H2 in O2 mixture
        secondary_gas: "O2"   # H2 in O2 mixture
        remaining_gas: "N2"   # Remaining gas (calculated)
        expected_gases: ["H2", "O2", "N2"]
      # Gas analysis configuration for purge operation
      purge_mode:
        primary_gas: "H2"     # H2 in N2 during purge
        secondary_gas: "N2"   # N2 purge gas
        remaining_gas: "O2"   # Remaining gas (calculated)
        expected_gases: ["H2", "N2", "O2"]
      
    bga_2:
      port: "COM3"
      name: "BGA02"
      gas_types: ["O2", "H2", "N2"]
      description: "Gas analyzer on oxygen header"
      # Gas analysis configuration for normal operation
      normal_mode:
        primary_gas: "O2"     # O2 in H2 mixture
        secondary_gas: "H2"   # O2 in H2 mixture
        remaining_gas: "N2"   # Remaining gas (calculated)
        expected_gases: ["O2", "H2", "N2"]
      # Gas analysis configuration for purge operation
      purge_mode:
        primary_gas: "O2"     # O2 in N2 during purge
        secondary_gas: "N2"   # N2 purge gas
        remaining_gas: "H2"   # Remaining gas (calculated)
        expected_gases: ["O2", "N2", "H2"]
      
    bga_3:
      port: "COM9"
      name: "BGA03"
      gas_types: ["H2", "O2", "N2"]
      description: "Gas analyzer on de-oxo unit"
      # Gas analysis configuration for normal operation
      normal_mode:
        primary_gas: "O2"     # H2 in O2 mixture
        secondary_gas: "H2"   # H2 in O2 mixture
        remaining_gas: "N2"   # Remaining gas (calculated)
        expected_gases: ["O2", "H2", "N2"]
      # Gas analysis configuration for purge operation
      purge_mode:
        primary_gas: "O2"     # H2 in N2 during purge
        secondary_gas: "N2"   # N2 purge gas
        remaining_gas: "H2"   # Remaining gas (calculated)
        expected_gases: ["O2", "N2", "H2"]

# CVM-24P Cell Voltage Monitor
cvm24p:
  device_type: "CVM-24P"
  connection: "USB"
  protocol: "Modbus RTU"
  
  # Cell Voltage Configuration
  cells:
    total_cells: 120
    groups: 6  # Group into 6 groups of 20 cells each
    voltage_range: [0, 5]  # Volts
      
  communication:
    baud_rate: 115200
    data_bits: 8
    stop_bits: 1
    parity: "None"
    timeout: 1.0

# System-Wide Configuration
system:
  # Data Acquisition Rates
  sample_rates:
    ni_daq: 100      # Hz - NI cDAQ analog inputs
    pico_tc08: 1     # Hz - Temperature readings
    bga244: 0.2      # Hz - Gas analyzer readings (every 5 seconds)
    cvm24p: 10       # Hz - Cell voltage readings
  
  # Calibration Settings
  calibration:
    auto_zero_on_startup: true  # Automatically apply zero offsets on connection
    allow_runtime_adjustment: false  # Prevent accidental calibration changes during tests
    calibration_date: "2025-06-04"   # Updated calibration date
    calibration_technician: "Engineering Team"
    
    # Zero Offset Application Rules
    zero_offset_rules:
      temperature_sensors: "Apply at ambient conditions (20-25°C)"
      pressure_sensors: "Apply at atmospheric pressure (0 psig) with sensors vented to atmosphere"
      current_sensor: "Apply with no load current (0 A)"
      gas_analyzers: "Apply in nitrogen purge environment"
      voltage_sensors: "Apply with stack at rest potential"
    
    # Calibration Notes (2025-06-04)
    calibration_notes:
      current_range_update: "Changed minimum current from 3.95mA to 4.0mA for standard 4-20mA scaling"
      pressure_sensor_1: "Zero offset -0.035 PSI applied to correct +0.035 PSI bias at 0 PSI"
      pressure_sensor_2: "Zero offset -0.066 PSI applied to correct +0.066 PSI bias at 0 PSI"
      calibration_method: "Sensors vented to atmosphere (0 psig) for zero point calibration"

 